package com.educacional.schoolacademicperiods.domain.exception;

public enum ExceptionCode {
    BUSINESS_EXCEPTION,
    RESOURCE_NOT_FOUND,
    EDTECH_NOT_FOUND,
    API_FIELDS_INVALID,
    APPLICATION_NOT_FOUND,
    DUPLICATE_RESOURCE_EXCEPTION,
    SERVICE_UNAVAILABLE_EXCEPTION,
    INTERNAL_SERVER_ERROR,
    EDTECH_SERVICE_UNAVAILABLE_EXCEPTION,
    ORGANIZATION_NOT_FOUND,
    ORGANIZATION_SERVICE_UNAVAILABLE_EXCEPTION,
    ACADEMIC_YEAR_NOT_FOUND,
    DUPLICATE_YEAR_EXCEPTION,
    ACADEMIC_PERIOD_NOT_FOUND,
    SCHOOL_NOT_FOUND,
    SCHOOL_SERVICE_UNAVAILABLE_EXCEPTION,
    EDUCATIONAL_NOT_FOUND,
    EDUCATIONAL_SERVICE_UNAVAILABLE_EXCEPTION,
    ACADEMIC_PERIOD_ALREADY_EXISTS,
    CATALOG_NOT_FOUND,
    INVALID_DATE,
    SCHOOL_CLASS_NOT_FOUND,
    ACADEMIC_PERIOD_LINKED_WITH_SCHOOL_CLASS,
    SCHOOL_CLASS_SERVICE_UNAVAILABLE_EXCEPTION;
}
